openapi: 3.0.3
info:
  title: WASAText API
  description: API for the WASAText application
  version: "1.0.0"
servers:
  - url: http://localhost:3000
    description: Local server
security:
  - BearerAuth: []

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      description: The user identifier is passed as the bearer token
      
  schemas:
    User:
      type: object
      properties:
        identifier:
          type: string
        username:
          type: string
        photoUrl:
          type: string
      required:
        - identifier
        - username
        
    Group:
      type: object
      properties:
        identifier:
          type: string
        name:
          type: string
        photoUrl:
          type: string
        members:
          type: array
          items:
            $ref: '#/components/schemas/User'
      required:
        - identifier
        - name
        
    Conversation:
      type: object
      properties:
        identifier:
          type: string
          description: Conversation identifier
        isGroup:
          type: boolean
        name:
          type: string
          description: Other person's username or group name
        photoUrl:
          type: string
        latestMessageTimestamp:
          type: string
          format: date-time
        latestMessagePreview:
          type: string
          description: Snippet of the text or an icon indicator for a photo
      required:
        - identifier
        - isGroup
        - name
        
    Reaction:
      type: object
      properties:
        emoticon:
          type: string
        user:
          $ref: '#/components/schemas/User'
      required:
        - emoticon
        - user

    Message:
      type: object
      properties:
        identifier:
          type: string
        conversationId:
          type: string
        sender:
          $ref: '#/components/schemas/User'
        timestamp:
          type: string
          format: date-time
        type:
          type: string
          enum: [text, photo]
        content:
          type: string
          description: Text content or photo URL
        status:
          type: string
          enum: [sent, received, read]
        reactions:
          type: array
          items:
            $ref: '#/components/schemas/Reaction'
      required:
        - identifier
        - conversationId
        - sender
        - timestamp
        - type
        - content
        - status

paths:
  /session:
    post:
      tags: ["login"]
      summary: Logs in the user
      description: |-
        If the user does not exist, it will be created,
        and an identifier is returned.
        If the user exists, the user identifier is returned.
      operationId: doLogin
      security: [] # No auth required for login
      requestBody:
        description: User details
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Maria
                  pattern: '^[a-zA-Z0-9]+$'
                  minLength: 3
                  maxLength: 16
              required:
                - name
        required: true
      responses:
        '201':
          description: User log-in action successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  identifier:
                    type: string
                    example: "abcdef012345"
  
  /users:
    get:
      tags: ["users"]
      summary: Search users
      operationId: searchUsers
      parameters:
        - name: username
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: List of users matching search
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'

  /users/me/name:
    put:
      tags: ["users"]
      summary: Update my username
      operationId: setMyUserName
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
                - name
      responses:
        '200':
          description: Name updated successfully
          
  /users/me/photo:
    put:
      tags: ["users"]
      summary: Update my profile photo
      operationId: setMyPhoto
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                photo:
                  type: string
                  format: binary
              required:
                - photo
      responses:
        '200':
          description: Photo updated successfully
          
  /groups:
    post:
      tags: ["groups"]
      summary: Create a new group
      operationId: createGroup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                members:
                  type: array
                  items:
                    type: string
                    description: User identifiers to invite
              required:
                - name
      responses:
        '201':
          description: Group created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Group'
                
  /groups/{groupId}/name:
    put:
      tags: ["groups"]
      summary: Update group name
      operationId: setGroupName
      parameters:
        - name: groupId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
                - name
      responses:
        '200':
          description: Group name updated

  /groups/{groupId}/photo:
    put:
      tags: ["groups"]
      summary: Update group photo
      operationId: setGroupPhoto
      parameters:
        - name: groupId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                photo:
                  type: string
                  format: binary
              required:
                - photo
      responses:
        '200':
          description: Group photo updated
          
  /groups/{groupId}/members:
    post:
      tags: ["groups"]
      summary: Add a user to the group
      operationId: addToGroup
      parameters:
        - name: groupId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
              required:
                - userId
      responses:
        '200':
          description: User added successfully
          
  /groups/{groupId}/members/me:
    delete:
      tags: ["groups"]
      summary: Leave a group
      operationId: leaveGroup
      parameters:
        - name: groupId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Left group successfully
          
  /conversations:
    get:
      tags: ["conversations"]
      summary: Get my conversations
      description: Returns a list of conversations sorted in reverse chronological order
      operationId: getMyConversations
      responses:
        '200':
          description: List of conversations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Conversation'
    post:
      tags: ["conversations"]
      summary: Create a new conversation
      description: Create a 1-on-1 conversation by passing another user's identifier
      operationId: createConversation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  description: Identifier of the user to start a conversation with
              required:
                - userId
      responses:
        '201':
          description: Conversation created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conversation'

  /conversations/{conversationId}:
    get:
      tags: ["conversations"]
      summary: Get conversation messages
      description: Get messages in a conversation in reverse chronological order
      operationId: getConversation
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of messages
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Message'
                  
  /conversations/{conversationId}/messages:
    post:
      tags: ["messages"]
      summary: Send a message
      operationId: sendMessage
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                text:
                  type: string
                photo:
                  type: string
                  format: binary
                replyTo:
                  type: string
                  description: Identifier of the message to reply to
      responses:
        '201':
          description: Message sent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
                
  /messages/{messageId}:
    delete:
      tags: ["messages"]
      summary: Delete a sent message
      operationId: deleteMessage
      parameters:
        - name: messageId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Message deleted

  /messages/{messageId}/forward:
    post:
      tags: ["messages"]
      summary: Forward a message
      operationId: forwardMessage
      parameters:
        - name: messageId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                conversationId:
                  type: string
                  description: The destination conversation identifier
              required:
                - conversationId
      responses:
        '201':
          description: Message forwarded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'

  /messages/{messageId}/comments/{emoticon}:
    put:
      tags: ["messages", "reactions"]
      summary: Comment (react) to a message
      operationId: commentMessage
      parameters:
        - name: messageId
          in: path
          required: true
          schema:
            type: string
        - name: emoticon
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Reaction added
          
    delete:
      tags: ["messages", "reactions"]
      summary: Uncomment (remove reaction) from a message
      operationId: uncommentMessage
      parameters:
        - name: messageId
          in: path
          required: true
          schema:
            type: string
        - name: emoticon
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Reaction removed
